### ISSUE TITLE
Funcionalidades de app videochamada

### ISSUE THREAD

**Issue by PabloGJBS** [pedrolucas12/WEB_RTC#2]
- [x] botão de ligar/desligar microfone
- [x] botão de ligar/desligar câmera
- [x] botão de levantar e abaixar mão 
- [x] marcar quem levantou a mão e em qual ordem 
- [x] Compartilhamento de tela

**Comment by PabloGJBS** [comment]
ta compartilhando tela mas a segunda pessoa na call não consegue ver

**Comment by JoaoBarreto03** [comment]
Funcionalidades completas
